/Library/MobileSubstrate/DynamicLibraries/iap.dylib|
/Library/MobileSubstrate/DynamicLibraries/iap.plist|
/var/mobile/Library/SBSettings/Toggles/iAPCracker/Toggle.dylib|
/Applications/AppCrackr.app/AppCrackr|
/Applications/SiNfuLCrack.app/SiNfuLCrack|
/Library/MobileSubstrate/DynamicLibraries/LocalIAPStore.dylib|
/Library/MobileSubstrate/DynamicLibraries/LocalIAPStore.plist|
/Library/PreferenceLoader/Preferences/LocalIAPStoreIcon.png|
/Library/PreferenceLoader/Preferences/LocalIAPStoreIcon@2x.png|
/var/lib/dpkg/info/anondev.localiapstore.list|
/Library/PreferenceLoader/Preferences/LocalIAPStore.plist|
/User/Library/Preferences/anondev.LocalIAPStore.plist|
/var/mobile/Library/Preferences/anondev.LocalIAPStore.plist|
/Library/MobileSubstrate/DynamicLibraries/Flipswitch.dylib|
/Library/MobileSubstrate/DynamicLibraries/Flipswitch.plist|
/Library/MobileSubstrate/DynamicLibraries/IAPFreeService.dylib|
/var/mobile/Library/Caches/com.crazydoraemon.IAPFree/Cache.db|
/Library/MobileSubstrate/DynamicLibraries/WeeLoader.dylib|
/Library/MobileSubstrate/DynamicLibraries/WeeLoader.plist|
/Library/MobileSubstrate/DynamicLibraries/libhide.dylib|
/Library/MobileSubstrate/DynamicLibraries/libhide.plist|
/Applications/IAPFree.app/Loader.dylib|
/Applications/IAPFree.app/IAPFree|
/Library/MobileSubstrate/DynamicLibraries/Activator.dylib|
/Library/MobileSubstrate/DynamicLibraries/Activator.plist
